### ISSUE TITLE
DNS-over-HTTPS via Cloudflare?

### ISSUE THREAD

**Issue by jplock** [loganmarchione/Firefox-tweaks#1]
What do you think about adding these settings:

* network.trr.mode = 3 (DNS over HTTPS only mode)
* network.trr.uri = https://mozilla.cloudflare-dns.com/dns-query
* network.trr.bootstrapAddress = 1.1.1.1

These were taken from https://www.ghacks.net/2018/04/02/configure-dns-over-https-in-firefox/

**Comment by loganmarchione** [comment]
I think that looks good! However, if Cloudflare's DNS goes down (unlikely), it would make your browser unusable.
I set all my DNS settings on my router, so all the devices in my house can share the same DNS settings, instead of just a single device.

Also, I'm skeptical of Cloudflare. I'm sure their DNS is better than your ISP, but I also believe they're collecting that data themselves.
https://www.reddit.com/r/privacy/comments/41cb4k/be_careful_with_cloudflare/
https://trac.torproject.org/projects/tor/ticket/24351
http://www.crimeflare.org:82/

**Comment by jplock** [comment]
Yea I trust Cloudflare more than my ISP at this point. :)

**Comment by loganmarchione** [comment]
Then I would say go for it. As mentioned, just remember that this will only apply to Firefox, on one device. If you switch browsers or devices, you'll be using your ISP's DNS.
